### ISSUE TITLE
Unlisting

### ISSUE THREAD

**Issue by bjsi** [browneyedsoul/RemNote-TextColorizer#5]
Hey do you mind unlisting the plugin? We are (finally) adding text color options in the next update :D. Thanks again!! 
![image](https://github.com/browneyedsoul/RemNote-TextColorizer/assets/58147075/cb5da3df-33cd-41ff-8b68-f6030ff13ce7)

**Comment by browneyedsoul** [comment]
Sure thing! I'm really excited to see RemNote heading in the right direction!
